### ISSUE TITLE
Using css rather js for visual effect

### ISSUE THREAD

**Issue by dizda** [WDI-HK-8/Formidable-web#54]
https://github.com/WDI-HK-8/Formidable-web/blob/master/app/assets/templates/forms/update.html#L37

CSS provide better performance for all visual effects

use the `:hover` css property rather than `ng-mouseover` angular directive (which implies much more complexity)

eg.

``` css
ul li a {
    display:none;
}

ul li:hover a {
    display:block;
}
```
